### ISSUE TITLE
logo background issue for namada https://shielded.live/validators?state=consensus

### ISSUE THREAD

**Issue by vchong** [hackbg/undexer#14]
Hi,

Is this the right place to report issues for https://shielded.live/validators?state=consensus? We uploaded our logo to https://shielded.live/validators/7C02D0D72034F41FDBEC1BCB106F58B401F2838B53B1A0F535D3FE0B3BA0B925, but it shows up with a lime green background. Is it expected?
![Screenshot from 2024-12-04 20-07-21](https://github.com/user-attachments/assets/f221db64-bd1b-4145-bb21-577761338422)

The logo looks fine on https://shielded.live/validators?state=consensus.
![Screenshot from 2024-12-04 20-07-52](https://github.com/user-attachments/assets/870a4758-29cb-4ffa-af1a-9b5d722ea951)

It also shows up fine on a different block explorer.
![Screenshot from 2024-12-04 20-09-48](https://github.com/user-attachments/assets/7de6d7d7-026a-4bd7-acf5-36ad057ea466)
![Screenshot from 2024-12-04 20-21-45](https://github.com/user-attachments/assets/d4f04c0e-9777-401d-a469-e31c85cbe977)

**Comment by egasimus** [comment]
Fixed, thanks for the report! We will also remove the white border shortly.

**Comment by vchong** [comment]
Great! Thank you so much!
